### ISSUE TITLE
有python版吗?

### ISSUE THREAD

**Issue by smallevil** [toolgood/ToolGood.Words#1]
python通用性更强一些吧?
不知道有没有python版?
一般这种都是出一个http的接口,做基础服务用的.
python import tornado很方便.

**Comment by toolgood** [comment]
抱歉，目前没有这个计划，
以后会有别的语言版本，如java，C++，Go语言的版本，估计要很久，目前没时间写。

**Comment by toolgood** [comment]
目前已添加了python版，地址如下
https://github.com/toolgood/ToolGood.Words/tree/master/python

**Comment by toolgood** [comment]
功能会一点一点补充上来
