### ISSUE TITLE
输入中存在空格，敏感词如何替换？

### ISSUE THREAD

**Issue by igaobingbing** [toolgood/ToolGood.Words#106]
var msg="你 好";
var searchTool = new StringSearchEx2();
searchTool.SetKeywords(["你好","世界"]);
var result = searchTool.Replace(msg, '*');
结果显示未替换。

**Comment by toolgood** [comment]
试试 IllegalWordsSearch ，也可以使用[ToolGood.TextFilter](https://github.com/toolgood/ToolGood.TextFilter)
