### ISSUE TITLE
模糊查找

### ISSUE THREAD

**Issue by FreeVB** [toolgood/ToolGood.Words#108]
请问模糊查找只能从第一个字符开始吗？
比如输入 ls,就不能显示俄罗斯的结果 。

textBox1.Text = string.Join(",", search.SearchTexts(textBox3.Text, true).ToArray());
比如这个，虽然是模糊匹配，但却是必须是从第一个字符开始。

**Comment by toolgood** [comment]
没有SearchTexts 这个方法名啊
