### ISSUE TITLE
有的偏僻汉字不能识别出拼音

### ISSUE THREAD

**Issue by armyhg** [toolgood/ToolGood.Words#11]
谢谢您的软件，在多音字识别方面超出了很多同类软件。不过还有的偏僻汉字不能识别出拼音，比如这几个字：“㘄䉄䬋䮚䚏㭁䖆”，望改进。
	"㘄": "lēng",
	"䉄": "léng",
	"䬋": "léng",
	"䮚": "lèng",
	"䚏": "lèng,lì,lìn",
	"㭁": "réng",
	"䖆": "niàng"

**Comment by toolgood** [comment]
目前，多音字识别的文字在0x4e00至0x9fa5之间，其他汉字扩展区还没有涉及到。

**Comment by toolgood** [comment]
先在这里做一个备注，有时间将内容补上。

字符集 | 字数 | Unicode 编码
-- | -- | --
基本汉字 | 20902字 | 4E00-9FA5
基本汉字补充 | 38字 | 9FA6-9FCB
扩展A | 6582字 | 3400-4DB5
扩展B | 42711字 | 20000-2A6D6
扩展C | 4149字 | 2A700-2B734
扩展D | 222字 | 2B740-2B81D
康熙部首 | 214字 | 2F00-2FD5
部首扩展 | 115字 | 2E80-2EF3
兼容汉字 | 477字 | F900-FAD9
兼容扩展 | 542字 | 2F800-2FA1D
PUA(GBK)部件 | 81字 | E815-E86F
部件扩展 | 452字 | E400-E5E8
PUA增补 | 207字 | E600-E6CF
汉字笔画 | 36字 | 31C0-31E3
汉字结构 | 12字 | 2FF0-2FFB
汉语注音 | 22字 | 3105-3120
注音扩展 | 22字 | 31A0-31BA
〇 | 1字 | 3007

**Comment by toolgood** [comment]
这个已完成，区间为 0x3400-0x9fD5， 偏僻汉字很多未验证
