### ISSUE TITLE
JAVA版本BaseMatch#SetKeywords 对应MatchKeywordBuild 拼接和拆分存在bug

### ISSUE THREAD

**Issue by dragonTalon** [toolgood/ToolGood.Words#116]
反馈一下,今天在使用BaseMatch的时候发现如果 同时配置 [ab][cd]的时候就会报错
原因是因为:
MatchKeywordBuild 在拆分的时候使用的是字符 0
String z = ((Character) (char) 0).toString();
而 KeywordBuild 在拼接的时候使用的是字符 1
  Character span = (char) 1;
所有有多个正则参数的时候就会报错
 java.util.MissingFormatArgumentException: Format specifier '%2$s'
------------------------------------------------------------------------------

`这里是1

    private static void KeywordBuild(Map<Integer, List<String>> parameterDict, int index, int end, String keyword,
                                     List<String> result) {

        **Character span = (char) 1;//这里是1**
        List<String> list = parameterDict.get(index);
        if (index == end) {
            for (int i = 0; i < list.size(); i++) {
                String item = list.get(i);
                result.add((keyword + span + item).substring(1));
            }
        } else {
            for (int i = 0; i < list.size(); i++) {
                String item = list.get(i);
                KeywordBuild(parameterDict, index + 1, end, keyword + span + item, result);
            }
        }
    }
`

`  这里是0

    protected List<String> MatchKeywordBuild(String keyword) throws Exception {

        StringBuilder stringBuilder = new StringBuilder();
        Map<Integer, List<String>> parameterDict = new Hashtable<Integer, List<String>>();
        SeparateParameters(keyword, stringBuilder, parameterDict);
        if (parameterDict.size() == 0) {
            List<String> al = new ArrayList<String>();
            al.add(stringBuilder.toString());
            return al;
        }
        List<String> parameters = new ArrayList<String>();
        KeywordBuild(parameterDict, 0, parameterDict.keySet().size() - 1, "", parameters);
        String keywordFmt = stringBuilder.toString();
        List<String> list = new ArrayList<String>();

        **String z = ((Character) (char) 0).toString();//这里是0** 
        for (int i = 0; i < parameters.size(); i++) {
            String item = parameters.get(i);
            String[] items = item.split(z);
            Object[] ls = new Object[items.length];
            for (int j = 0; j < ls.length; j++) {
                ls[j] = items[j];
            }
            String t = String.format(keywordFmt, ls);
            if (list.contains(t) == false) {
                list.add(t);
            }
        }
        return list;
    }`
------------------------------------------------------------------------
我在本地已经修复这个问题了,希望博主也能修复一下这个问题.

**Comment by toolgood** [comment]
谢谢，指出问题
