### ISSUE TITLE
result not right.

### ISSUE THREAD

**Issue by RocherKong** [toolgood/ToolGood.Words#17]
private IllegalWordsSearch illegalWordsSearch = null;
   illegalWordsSearch = new IllegalWordsSearch();
   private string s = "中国|zg人|abc";
illegalWordsSearch.SetKeywords(s.Split('|'));
 illegalWordsSearch.Replace("我是中美国人厉害中国完美ａｂｃddb好的", '*');

then result is:我是中美国人厉害************
expected result is:我是中美国人厉害**完美***ddb好的

**Comment by toolgood** [comment]
谢谢。这个问题已解决。
