### ISSUE TITLE
请问作者，IllegalWordsSearch.SetBlacklist的作用是什么？

### ISSUE THREAD

**Issue by foresightyj** [toolgood/ToolGood.Words#18]
我看单元测试，只是放的一个数字的数组，BlackListType这个enum也没有看懂。可以麻烦作者在readme里面稍微解释一下吗？谢谢！

**Comment by DHclly** [comment]
黑名单列表吧

**Comment by foresightyj** [comment]
@DHclly 
属性名字我看得懂什么意思，但是里面每个数字的值是什么意思呢？

**Comment by toolgood** [comment]
添加SetBlacklist方法原因， https://github.com/toolgood/ToolGood.Words/issues/9
