### ISSUE TITLE
您好，有关跳词和黑名单设置

### ISSUE THREAD

**Issue by GeassAce** [toolgood/ToolGood.Words#19]
这两个功能不太懂有什么用，跳词设置后，用FindAll依旧能查出结果，看来不是设置能跳过某个词的功能，那个黑名单级别也是没怎么看懂，作者能不能说明下？谢谢了

**Comment by toolgood** [comment]
请问，能否提供一下测试代码

**Comment by toolgood** [comment]
黑名单设置原因： https://github.com/toolgood/ToolGood.Words/issues/9

**Comment by toolgood** [comment]
跳词设置后，将IllegalWordsSearch类的UseSkipWordFilter设置成true
