### ISSUE TITLE
直接使用Regex.Matches 不是还可以?

### ISSUE THREAD

**Issue by chencidi** [toolgood/ToolGood.Words#2]
插曲：在细查Regex.Matches神奇3ms，我发现Regex.Matches有一个小问题，

**Comment by toolgood** [comment]
Regex.Matches神奇3ms。
原因：
使用Regex.Matches时，它只返回一个matchcollection，还没有真正计算，真正计算是在你从这个collection拿结果的时候，这个和iqueryable一个道理。
