### ISSUE TITLE
敏感词越多导致初始化极慢

### ISSUE THREAD

**Issue by xiaobingit** [toolgood/ToolGood.Words#21]
你好，  测试中1W多的敏感词加载需要10多秒， 如果到5万，甚至10万敏感词，那么初始化基本卡死掉了，无法使用， 有劳作者测试和改进下

**Comment by toolgood** [comment]
使用 IllegalWordsSearch、StringSearchEx、WordsSearchEx ，这几个类有Save、Load方法，可以加快初始化。
