### ISSUE TITLE
长短不一的敏感词会重复命中_要如何设置

### ISSUE THREAD

**Issue by zhangzw218** [toolgood/ToolGood.Words#24]
var iws = new IllegalWordsSearch();
            iws.SetKeywords("烦死了,烦,死,了".Split(','));
            iws.UseDuplicateWordFilter = true;
            iws.UseIgnoreCase = true;
            iws.UseDBCcaseConverter = true;

            //act
            List<IllegalWordsSearchResult> res = iws.FindAll("果然是烦死了");

            //assert
            //现在的问题是，res.count=4，会同时命中：“烦死了”“烦”“死”“了”这四个敏感词。
            //有办法设置，按最小长度或者最大长度命中，不要重复么。

            //如何确保只命中一次，比如只命中“烦死了”
            Assert.AreEqual(1, res.Count);

            //或者说，只命中三次，比如命中了“烦”“死”“了”
            Assert.AreEqual(3, res.Count);`

![aa](https://user-images.githubusercontent.com/40768649/61109230-fe5cab80-a4b6-11e9-9b67-ddb44bf7e037.png)

**Comment by toolgood** [comment]
这个可以通过位置的开始位置、长度来过滤。
