### ISSUE TITLE
PinYinSearch大量占用内存有什么好的方案

### ISSUE THREAD

**Issue by agilelab** [toolgood/ToolGood.Words#26]
我实际测了一下，使用了67万关键字，12M文本，SetKeywords，2秒左右，占用内存1.7G，这还不算多大的数据情况下，有点招不住，另外，看到FirstPinYinNode=>PinYinNode=>ChineseNode,也就是说树的深度随着指数增加，在大量数据的情况假设按管件字20字，深度60，每三级节点，第一级26字母，第二级，常见拼音406个，第三级，中文字符20903个，这样下来，搜索的深度和广度是否太大了一些，是否有更好的解决方案，能否在设计上做一些优化。

**Comment by toolgood** [comment]
使用 PinYinSearchEx

**Comment by agilelab** [comment]
针对大数据量，建议调整一下索引机制，我改用了两级索引方案，拼音=》汉子，汉字构建Trie树，增加汉子初始矩阵和状态转移即可。

**Comment by toolgood** [comment]
多谢提醒

**Comment by toolgood** [comment]
PinYinSearch，PinYinSearchEx设计不合理，已删除，最新方案使用 PinyinMatch，主要是减少内存量，
