### ISSUE TITLE
IllegalWordsSearch 无法识别数字敏感字？

### ISSUE THREAD

**Issue by ijustkeepmoving** [toolgood/ToolGood.Words#30]
`
string text = "A1002481003吃饭";
        var keywords = new string[] { "248" };
        var iws = new IllegalWordsSearch();
        var ss = new StringSearch();
        var sse = new StringSearchEx();
        iws.SetKeywords(keywords);

        //无结果
        var iwsFirst = iws.FindFirst(text);
        var iwsAll = iws.FindAll(text);

        //正常识别出248
        ss.SetKeywords(keywords);
        var ssFirst = ss.FindFirst(text);
        var ssAll = ss.FindAll(text);
        
        //正常识别出248
        sse.SetKeywords(keywords);
        var sseFirst = sse.FindFirst(text);
        var sseAll = sse.FindAll(text);
`
![1](https://user-images.githubusercontent.com/12046942/68107680-97a94500-ff20-11e9-9d85-b471c3581674.jpg)
![2](https://user-images.githubusercontent.com/12046942/68107681-97a94500-ff20-11e9-9615-d1efffb7fad9.jpg)
![3](https://user-images.githubusercontent.com/12046942/68107682-97a94500-ff20-11e9-8b8d-4e6d357ad675.jpg)

**Comment by ijustkeepmoving** [comment]
使用的是最新版本：2.3.4.2

**Comment by toolgood** [comment]
原因是这样的，IllegalWordsSearch 会判断文本左右的字符，防止敏感词误查。如 smile 不会被 sm 匹配到。

**Comment by ijustkeepmoving** [comment]
@toolgood smile按说含有sm,匹配到才是正确的结果吧

**Comment by toolgood** [comment]
IllegalWordsSearch  匹配英文单词、整串数字，不是匹配字符，匹配字符使用其他类。。。

**Comment by ijustkeepmoving** [comment]
@toolgood sorry 搞错了~

**Comment by ijustkeepmoving** [comment]
那用其它的类来做，就没有什么设置跳词这些功能哒，比如敏感词FUCK，用户输成 F U C K，这样就不能匹配到呢，一直用IllegalWordsSearch 这个就是看到有设置跳词的功能。我们的敏感词有中文、英文、
数字串这些。有什么好的办法分享一下吗？
