### ISSUE TITLE
能不能介绍下过滤的算法和实现方式

### ISSUE THREAD

**Issue by worldunfair** [toolgood/ToolGood.Words#31]
能不能介绍下过滤的算法和实现方式，公司引入算法需要对技术做下调研，但是在下才疏学浅，能不能介绍下实现方式和相关算法。

**Comment by toolgood** [comment]
原本想写一篇文章的，最近时间不够，再加上人懒，就没写。。。。
设计初期可以参考我这篇 https://www.cnblogs.com/toolgood/p/6284718.html
后来为了加快加载速度，使用数组保存，改写代码后，速度又提升了一个档次，
为了减少数组内存量，减少熵，匹配时，使用先进行预断字符串是否存在，速度又提升了一个档次，
使用unsafe，速度又提升了。。。

**Comment by GravityQ** [comment]
同求大牛写一下算法思路

**Comment by toolgood** [comment]
ToolGood.Words算法过滤敏感词优化原理 （收费30元，一顿KFC）
https://mianbaoduo.com/o/bread/YZ2Yk5hy
本人开始创业了，创业初期比较困难，文章收费混口饭吃。
