### ISSUE TITLE
java要使用模糊搜索需要用哪个类 比如说 微信骚聊和微信聊 都是敏感词要怎么去使用模糊搜索功能

### ISSUE THREAD

**Issue by worldunfair** [toolgood/ToolGood.Words#33]
java要使用模糊搜索需要用哪个类 比如说 微信骚聊和微信聊 都是敏感词要怎么去使用模糊搜索功能

**Comment by toolgood** [comment]
java的模糊搜索 还没有移植过去。。。

**Comment by toolgood** [comment]
可以使用StringSearch、StringSearchEx、WordsSearch、WordsSearchEx、IllegalWordsSearch都可以用于过滤查询，请将微信骚聊和微信聊  加入 关键字组内  使用SetKeywords 再查找就可以了

c#版本来说StringSearchEx、WordsSearchEx性能更好一点，缺点是词库太大生成太慢。建议使用StringSearch、WordsSearch、IllegalWordsSearch。
