### ISSUE TITLE
建议增加 汉字转拼音带上声调

### ISSUE THREAD

**Issue by ulyanovsk** [toolgood/ToolGood.Words#39]
中文转拼音，如果带上声调，就完美了

**Comment by toolgood** [comment]
暂时没有办法，搜狗的拼音库是不带声调的。。。。

**Comment by toolgood** [comment]
准确的来源不好找啊
吐槽一下，
hotoo/pinyin项目 5000多个星，里面好多bug
百度翻译、百度百科、百度汉语 全在打架，，，，
看了几个项目都是很差的。。。
哎，慢慢整理吧。。。

**Comment by ulyanovsk** [comment]
https://github.com/hyjiacan/Pinyin4NET，这个项目（不是我的），中文转拼音，带声调的，我试用过，还行，你看能不能合到项目里来。（因为其他性能还是你的项目好太多）

**Comment by toolgood** [comment]
上面这个项目只支持 0x4E00~0x9FA5 ，这个区间【0x3400, 0x4DB5】还是没有的

**Comment by ulyanovsk** [comment]
是的，言之有理

**Comment by toolgood** [comment]
更新完毕，但是 偏僻汉字很多未验证，没有时间一个一个验证

**Comment by ulyanovsk** [comment]
给力的项目，👍
