### ISSUE TITLE
推荐功能

### ISSUE THREAD

**Issue by chencidi** [toolgood/ToolGood.Words#4]
推荐功能:
1、匹配大小写过滤
 2、匹配全角半角过滤
 3、匹配过滤停顿词过滤。
 4、敏感词重复词过滤。

资料: http://blog.csdn.net/fengshizty/article/details/52373005

**Comment by toolgood** [comment]
请使用IllegalWordsSearch类
1、匹配大小写过滤：已有。
2、匹配全角半角过滤：已有。
3、匹配过滤停顿词过滤：如果是删除停顿词，就在过滤列表中添加停顿词， 如果是跳过停顿词，那就没必要修改，因为增加检测停顿词，反而让程序减慢速度。
4、敏感词重复词过滤：已有。

如果是单纯检测敏感词，可以使用IllegalWordsQuickSearch类。

**Comment by chencidi** [comment]
过滤列表中添加停顿词?  在哪里有过滤列表?

**Comment by chencidi** [comment]
敏感词重复词过滤 使用IllegalWordsSearch测试好像不行.   从代码中也没有找到相应的代码.  能帮忙指点一下吗?

**Comment by toolgood** [comment]
今天仔细看了一下停顿词，代码中有过滤停顿词的功能

**Comment by toolgood** [comment]
敏感词重复词，好像真的没有，不过可以在过滤前预处理文本，
如果添加过滤重复，估计要改最底层的算法。。。

**Comment by toolgood** [comment]
代码已更新，已添加以下两点功能：
匹配过滤停顿词过滤，敏感词重复词过滤
