### ISSUE TITLE
10W词库，加载非常慢

### ISSUE THREAD

**Issue by fanshifei** [toolgood/ToolGood.Words#43]
10W词库，加载非常慢，1个小时都没有加载完

**Comment by toolgood** [comment]
建议使用带Ex的方法，后期会改进加载算法

**Comment by toolgood** [comment]
加载算法已更新，请尝试一下，谢谢反馈

**Comment by toolgood** [comment]
新算法，使用WordsSearch，7.W词组大概在2秒内。。WordsSearchEx很慢

**Comment by toolgood** [comment]
如果你是用C#，可以试用一下3.X分支下的BigWordsSearchEx类，查询速度大于WordsSearch  小于WordsSearchEx 。如果是其他语言请再等等
