### ISSUE TITLE
繁简转换缺失  勳/勛 vs 勋

### ISSUE THREAD

**Issue by bc4250** [toolgood/ToolGood.Words#44]
勋  ->转繁体只有 勛  这个不算问题，因为"勳"是异体字
但是 勳->转简体时还是 勳  这个建议修正码表.

**Comment by bc4250** [comment]
補充幾個語料參考， 前路漫漫...
https://www.zhihu.com/question/23570519
http://old.pep.com.cn/xgjy/hyjx/hyxxzy/hyxx/yffd/201009/t20100901_855565.htm

香港朋友要求的是“行” (row)，台湾朋友做出来的是“列” (column)。因为台湾的 row 就是“行”，column 好像叫“栏位”
Field 字段 vs 欄位
再比如「算法」就会转成「演算法」
"项目" 在台湾的意思是 bullet list 里面的一项（Item），而不是 project 的意思，台湾的 project 经常译作“专案”

發現一個相關項供參考.
https://github.com/Authenticator-Extension/Authenticator

**Comment by toolgood** [comment]
谢谢反馈

**Comment by toolgood** [comment]
提供的参考有问题，我找到一个
https://github.com/BYVoid/OpenCC

**Comment by bc4250** [comment]
wow， 是的， 你找的这个更棒！

**Comment by toolgood** [comment]
类库更新了，繁简转换使用 OpenCC 的字典了
