### ISSUE TITLE
方法名统一一下吧

### ISSUE THREAD

**Issue by ulyanovsk** [toolgood/ToolGood.Words#47]
拼音：英文翻译就是“Pinyin”，项目中有些方法名是“PinYin”，有些又是"Pinyin"，建议都用“Pinyin”

**Comment by toolgood** [comment]
谢谢反馈

**Comment by ulyanovsk** [comment]
项目最近推进的速度明显加快，赞👍


| |
胡中山
|
|
ulyanovsk@126.com
|
签名由网易邮箱大师定制


在2020年04月12日 09:21，ToolGood<notifications@github.com> 写道：

谢谢反馈
