### ISSUE TITLE
 繁体改简体 有一处感觉不对啊

### ISSUE THREAD

**Issue by liuliu6000** [toolgood/ToolGood.Words#50]
比如：乾清宫 ，繁体变简体 ，变成了 "干清宫"， 貌似在你的 FindAll  有问题的，非单字的没有匹配到，我用的是python

**Comment by toolgood** [comment]
嗯，原因找到了，乾的编码是0x20094，范围大于0xffff。
python,javascript的char 最大值为0xffffffff
java,C#的char编码最大值为0xffff

**Comment by toolgood** [comment]
上面回复的点问题，Translate类 _t2s_t 字段  _t2s_s 字段 没有“乾清宫” 两个字，
不过上面也是一个bug

**Comment by toolgood** [comment]
已修改
