### ISSUE TITLE
java 版本 TrieNodeEx 的 Rank(oneStart, start, seats, seats2, has) 方法耗时比较大

### ISSUE THREAD

**Issue by fanshifei** [toolgood/ToolGood.Words#51]
java版本，循环调用TrieNodeEx的Rank(oneStart, start, seats, seats2, has)方法的时候，如果list的size较大会耗时很严重，甚至会卡死。

**Comment by toolgood** [comment]
是的，关键词量比较大时会耗时非常严重，暂时使用WordsSearchEx类来代替吧。

**Comment by toolgood** [comment]
WordsSearchEx类，虽然功能没有IllegalWordsSearch全，但速度还是挺快的。

**Comment by fanshifei** [comment]
WordsSearchEx FindAll方法，敏感词识别不全
