### ISSUE TITLE
内存占用

### ISSUE THREAD

**Issue by bao-qian** [toolgood/ToolGood.Words#53]
你好，
使用了你的库 c# 版本，发现内存占用很大。

程序启动的时候调用二十次左右 `WordsHelper.GetFirstPinyin`，内存占用会飙升至 1G 左右。
有什么好办法可以减小内存占用吗？

memory profile 结果
![image](https://user-images.githubusercontent.com/1169912/82329518-01e48b80-9a14-11ea-97fd-2d7d0990fe45.png)

**Comment by toolgood** [comment]
能上传一下测试代码吗？

**Comment by bao-qian** [comment]
代码在这里，我尽快上传一份可以复现的最小代码。

https://github.com/Wox-launcher/Wox/blob/master/Wox.Infrastructure/Alphabet.cs#L41-L47

**Comment by toolgood** [comment]
仔细研究代码后，PinyinDict是懒加载，只加载一次，最多消耗87M，使用WordsSearchEx来加载可降低到40M，感觉是多线程（并发情况下）没有加锁。
就在刚才测试了代码，发现你的代码的确是在多线程执行的。

**Comment by bao-qian** [comment]
@toolgood 
能不能多线程下共享加载资源？

**Comment by toolgood** [comment]
已修改，最新使用3.0.1.2 版本

**Comment by toolgood** [comment]
我看了一下Wox使用内存在140M左右

**Comment by bao-qian** [comment]
感谢，确认已修复。
