### ISSUE TITLE
某个关键字不能替换

### ISSUE THREAD

**Issue by mysll** [toolgood/ToolGood.Words#54]
@Test
    public void replace() {
        IllegalWordsSearch search = new IllegalWordsSearch();
        search.SetKeywords(Arrays.asList("test", "world", "this", "hello", "monster"));
        String result = search.Replace("test, hahaha, this is a hello world", '*');
        System.out.println(result);
    }

输出
****, hahaha, **** is a hello *****
hello 为什么替换不掉呢?

**Comment by toolgood** [comment]
C#语言是没有这个问题，JAVA语言我得研究一下。

**Comment by toolgood** [comment]
JAVA语言IllegalWordsSearch的bug修复好了
