### ISSUE TITLE
大佬能讲一下_key，_next，_guides这些数组的作用吗？

### ISSUE THREAD

**Issue by GravityQ** [toolgood/ToolGood.Words#58]
大佬能讲一下_key，_next，_guides这些数组的作用吗？

**Comment by seasun** [comment]
https://www.cnblogs.com/toolgood/p/6284718.html

**Comment by toolgood** [comment]
ToolGood.Words算法过滤敏感词优化原理 （收费30元，一顿KFC）
https://mianbaoduo.com/o/bread/YZ2Yk5hy
本人开始创业了，创业初期比较困难，文章收费混口饭吃。
