### ISSUE TITLE
大佬仍然有关键词匹配不到

### ISSUE THREAD

**Issue by syt0438** [toolgood/ToolGood.Words#59]
- tuidang
- yuce

**Comment by seasun** [comment]
private static StringSearch wordsSearch = null;
    private static WordsMatch wordsSearch = null;
经测，包4个小时前博主更新的版本，只有这两个类没有问题，java版，10W次性能几乎一致

**Comment by syt0438** [comment]
> private static StringSearch wordsSearch = null;
> private static WordsMatch wordsSearch = null;
> 经测，包4个小时前博主更新的版本，只有这两个类没有问题，java版，10W次性能几乎一致

实测，更新了博主最新版本，仍然有未知的一部份敏感词无法匹配， 包括tuidang和yuce。

**Comment by toolgood** [comment]
> 
> 
> > private static StringSearch wordsSearch = null;
> > private static WordsMatch wordsSearch = null;
> > 经测，包4个小时前博主更新的版本，只有这两个类没有问题，java版，10W次性能几乎一致
> 
> 实测，更新了博主最新版本，仍然有未知的一部份敏感词无法匹配， 包括tuidang和yuce。

请提交一下测试代码

**Comment by toolgood** [comment]
由于@syt0438 没有提供测试代码及词库，这个Issues永远不能解决，只好进行关闭处理。
