### ISSUE TITLE
有个别乱码现象

### ISSUE THREAD

**Issue by rindybo** [toolgood/ToolGood.Words#6]
utf8中文有个别乱码现象，用的是IllegalWordsSearch
使用前
` {"id":"政府行业###中国###中国人民###人民大学","count":725},{"id":"政府行业###中国###中国人民###人民共和国","count":279},{"id":"政府行业###中国###中国人民###中国人民解放军","count":227}`
使用后
` {"id":"政府行业###中国###中国人民###人民大学","count":725},{"id":"政府行业###中国###中国人��###人民共和国","count":279},{"id":"政府行业###中国###中国人民###中国人民解放军","count":227}` 
可以看到“民”这个字在多个地方出现，但只有一个是乱码

**Comment by toolgood** [comment]
看一下测试关建字和测试文本

**Comment by rindybo** [comment]
谢谢回复，早上起来突然就好了
