### ISSUE TITLE
大佬，代码能稍微加点注释吗

### ISSUE THREAD

**Issue by CaoDeju** [toolgood/ToolGood.Words#61]
想研究下大佬写的算法实现思路，但是代码注释有点少，研究起来有点费劲，有些属性都不知道是干嘛的。。。，小弟拜谢

**Comment by toolgood** [comment]
目前没时间，有空时再加吧。

**Comment by toolgood** [comment]
ToolGood.Words算法过滤敏感词优化原理 （收费30元，一顿KFC）
https://mianbaoduo.com/o/bread/YZ2Yk5hy
本人开始创业了，创业初期比较困难，文章收费混口饭吃。
