### ISSUE TITLE
这个如果新建一个新的项目的话resourceName要怎么改呢？

### ISSUE THREAD

**Issue by nileixing** [toolgood/ToolGood.Words#63]
const string resourceName = "ToolGood.Words.dict.pyIndex.txt.z";
Stream sm = ass.GetManifestResourceStream(resourceName);

这个ToolGood.Words改成新项目的命名空间或用老的这个sm都取不到，这个读取文件可以用路径的方式么

**Comment by toolgood** [comment]
可以的
