### ISSUE TITLE
简体转繁体，纰漏

### ISSUE THREAD

**Issue by ulyanovsk** [toolgood/ToolGood.Words#65]
简体“里”转繁体，应该是“裏”,现在繁体还是“里”

**Comment by ulyanovsk** [comment]
但繁体转简体，是好的，”里“字

**Comment by toolgood** [comment]
我测试过， 下面的代码是正常的
```` cs
            var t = WordsHelper.ToTraditionalChinese("里");
            Assert.AreEqual("裏", t);
````


项目采用的是 https://github.com/BYVoid/OpenCC 的字典
我看了一下，STPhrases.txt 里面有大量的简体“里” 不转成 “裏”
比如： 
简体      =>    繁体
一日千里	一日千里
一泻千里	一瀉千里
万里	萬里

**Comment by ulyanovsk** [comment]
原来是这样，还要看词组的，明白了




| |
胡中山
|
|
邮箱：ulyanovsk@126.com
|

签名由 网易邮箱大师 定制

在2020年09月30日 11:22，ToolGood 写道：

我测试过， 下面的代码是正常的

vart=WordsHelper.ToTraditionalChinese("里");

            Assert.AreEqual("裏", t);

项目采用的是 https://github.com/BYVoid/OpenCC 的字典
我看了一下，STPhrases.txt 里面有大量的简体“里” 不转成 “裏”
比如：
简体 => 繁体
一日千里 一日千里
一泻千里 一瀉千里
万里 萬里

**Comment by ulyanovsk** [comment]
原来简体转繁体有语境，多谢解答
