### ISSUE TITLE
大佬，导入字典数据，检索，报错

### ISSUE THREAD

**Issue by ulyanovsk** [toolgood/ToolGood.Words#68]
代码1如下：
var search = new PinyinMatch();
search.SetKeywords(keywords);
search.Find("野huo");

代码2如下：
var search = new StringSearchEx3();
search.SetKeywords(keywords);
search.FindAll("野火");

keywords来自字典文件：数据量:351121
https://res.lims.ltd/dict.txt

两段代码报一样的错：
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ToolGood.Words.internals.PinyinDict.GetPinyinList(String text, Int32 tone)
   at ToolGood.Words.PinyinMatch.SetKeywords(ICollection`1 keywords)

**Comment by toolgood** [comment]
这是结巴分词库。。。我看一下

**Comment by ulyanovsk** [comment]
但把数据删到30W以内，就不报错了

**Comment by toolgood** [comment]
代码没问题
``` cs
        /// <summary>
        /// https://github.com/toolgood/ToolGood.Words/issues/65
        /// </summary>
        [Test]
        public void IssuesTest_68_1()
        {
            var txts = File.ReadAllLines("_texts/dict.txt");
            var keywords = new List<String>();
            foreach (var item in txts)
            {
                keywords.Add(item.Split(" \t".ToCharArray(), StringSplitOptions.RemoveEmptyEntries)[0]);
            }
            var search = new PinyinMatch();
            search.SetKeywords(keywords);
            var ts = search.Find("野huo");
            Assert.AreEqual(5, ts.Count);
        }
```

**Comment by toolgood** [comment]
StringSearchEx3 的有问题，建议使用 StringSearchEx

**Comment by ulyanovsk** [comment]
查明，报错是编码问题，哎，多谢！
