### ISSUE TITLE
移植到别的项目中使用就会出问题

### ISSUE THREAD

**Issue by mycfeifei** [toolgood/ToolGood.Words#70]
IllegalWordsSearch类的load方法在本项目中正常使用（文件为项目中的IllegalWordsSearch.dat），但是移植到别的项目中（编码为UTF-8）就会出现_guides数组read方法读取超长。报错：wrong flag: 191

**Comment by toolgood** [comment]
请查看一下，IllegalWordsSearch是不是使用的老版的，新版的IllegalWordsSearch是没有_guides

**Comment by toolgood** [comment]
windows 下默认GBK的。。。linux使用的是utf-8

**Comment by toolgood** [comment]
新版的IllegalWordsSearch已强制使用utf-8

**Comment by mycfeifei** [comment]
已经可以了。旧版换项目读取文件后结果有差异的原因尚不清楚，我换了3个项目其中2个可以正常使用，一个会报错。现在用的是新版，旧的敏感词文件不能使用后，我从网上找了一些敏感词，并按照项目提供的demo重新生成新的文件并使用它就没问题了。
