### ISSUE TITLE
词典里有的关键词识别不出来

### ISSUE THREAD

**Issue by Sugarsugarzz** [toolgood/ToolGood.Words#72]
IllegalWordsSearch searcher = new IllegalWordsSearch();
        List<String> list = new ArrayList<>();
        try (Stream<String> stream = Files.lines(ResourceUtils.getFile("classpath:dict/SensitiveDict.txt").toPath(), StandardCharsets.UTF_8)) {
            stream.forEach( word ->{
                list.add(word);
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
        searcher.SetKeywords(list);

        List<IllegalWordsSearchResult> words = searcher.FindAll(content);
        words.forEach(word -> {
            System.out.println(word.Keyword + " - " + word.MatchKeyword);
        });

测试代码如上，在SensitiveDict中的许多关键词，在句子中却识别不出来。
目前SensitiveDict词典的大小在3000个词条左右。
如果SensitiveDict就放几条测试词条，就能够识别出来，但到3000个左右就识别不了，请问大佬是什么情况呢...

**Comment by toolgood** [comment]
正常情况下是不会显示 � 的，显示有� 说明字符集出错了

**Comment by Sugarsugarzz** [comment]
呃..�这个符号不是词典里的...
情况是，比如我的词典里有台湾这个词，当词典扩充到3000多个以后，测试文本中的台湾没有识别出来，在小规模词典时能够识别出来，有点疑惑。

**Comment by Sugarsugarzz** [comment]
StringSearch stringSearch = new StringSearch();
    List<String> list = new ArrayList<>();
    try (Stream<String> stream = Files.lines(ResourceUtils.getFile("classpath:dict/SensitiveDict.txt").toPath(), StandardCharsets.UTF_8)) {
        stream.forEach( word ->{
            list.add(word);
        });
    } catch (Exception e) {
        e.printStackTrace();
    }
    stringSearch.SetKeywords(list);
    List<String> words = stringSearch.FindAll(content);

使用 StringSearch 就没有问题，词典中的词都能够从文本中识别出来。但是 StringSearch 又没法识别 台;湾 这种情况.

**Comment by toolgood** [comment]
你还是检查一下敏感词库吧。。。

**Comment by inlovingrest** [comment]
我也出现了这种问题，有的字符能识别，有的不能识别

**Comment by toolgood** [comment]
请自行检查一下词库。
你们没有提供测试代码，也没提供词库。。。

**Comment by toolgood** [comment]
由于@Sugarsugarzz @inlovingrest  没有提供测试代码及词库，这个Issues永远不能解决，只好进行关闭处理。
