### ISSUE TITLE
文本分词

### ISSUE THREAD

**Issue by doraoe** [toolgood/ToolGood.Words#75]
请问算法有对需筛查文本进行中文分词吗

**Comment by toolgood** [comment]
目前没有分词功能，
其实分词很简单，要有分词库，再加动态规则就可以了。
再加上HMM就可以判断未知新词

**Comment by toolgood** [comment]
目前本库不适合做分词，因为追求性用占用了大量的内存。。。
内存优化版本我暂时不想开源。。。
