### ISSUE TITLE
PinyinMatch建议增加 追加关键词 的方法

### ISSUE THREAD

**Issue by HeyHeyPo** [toolgood/ToolGood.Words#78]
PinyinMatch的SetKeywords方法每次调用都会直接覆盖掉_keywords，如果中途需要追加部分关键词，就只能重新加载全部关键词，所以最好是能提供在后面追加的方法。

**Comment by toolgood** [comment]
最近在整理敏感词库...有时间会补上。。。
如果你有时间，可以贡献一下代码

**Comment by toolgood** [comment]
C#使用PinyinMatch<T>， Java使用PinyinMatch2<T>，可以自定义扩展

**Comment by toolgood** [comment]
粗略地回顾了一下代码，发现性能还可以提升一点，
优化方案是使用 `Bloom Filter`。
有时间再改吧。。。
