### ISSUE TITLE
能否简介下使用的什么算法？

### ISSUE THREAD

**Issue by OptimusMX** [toolgood/ToolGood.Words#83]
作者开源辛苦，能否在首页介绍下实现方式，大致说下就可以，让我们使用这套代码的人，跟别人说的时候，能吹出点东西。辛苦。

**Comment by fourierxue** [comment]
看了下BaseSearchEx的代码，貌似用到了字典树

**Comment by wpf1070816930** [comment]
AC自动机多模匹配

**Comment by toolgood** [comment]
ToolGood.Words算法过滤敏感词优化原理 （收费30元，一顿KFC）
https://mianbaoduo.com/o/bread/YZ2Yk5hy
本人开始创业了，创业初期比较困难，文章收费混口饭吃。

**Comment by wenlifan** [comment]
文章支持， 可是只要3块呀
