### ISSUE TITLE
过滤时临时添加不过滤项

### ISSUE THREAD

**Issue by tkezyo** [toolgood/ToolGood.Words#9]
需求是所有的客户原则上要过滤全部的敏感词,但是个别用户有白名单.这样在这个用户在过滤的时候就需要跳过这些单词.
我不知道是重新初始化好,还是每找到一个后再验证是否在白名单好.现在我选的是后者.

**Comment by toolgood** [comment]
先判断是否为白名单用户，如果是，就使用WordsSearch（或WordsSearchEx）的FindAll，这个查找出的敏感词是带位置的、带关键字索引的，这样就很方便确定用户是否拥有这个白名单。

**Comment by toolgood** [comment]
年后准备改写IllegalWordsSearch，会考虑这个需求的。

**Comment by toolgood** [comment]
修改的IllegalWordsSearch有黑名单功能，黑名单可以指定31个组

步骤：
使用SetKeywords方法后，使用SetBlacklist方法，并且设置UseBlacklistFilter=true; 最后使用FindAll(text, BlacklistType.Level01)方法

**Comment by toolgood** [comment]
关键字与黑名单列表的长度要一样长

**Comment by tkezyo** [comment]
非常感谢
