### ISSUE TITLE
敏感词库包含 `(` 左括号就报错

### ISSUE THREAD

**Issue by runtop** [toolgood/ToolGood.Words#93]
敏感词库包含 `(` 左括号就报错，比如：

`fu(|fuc|FUCK|Fuck|fuck|fuck fuck|Fuck You|fuck you`

错误为：
`【fu(】出错了，最后一位不为)`

**Comment by toolgood** [comment]
StringMatch、WordsMatch 都是向正则方向探索的中间版本。

左括号 前加 \ 表转义。。。。

**Comment by toolgood** [comment]
现在不建议使用StringMatch、WordsMatch版本
